#!/usr/bin/env bash

source ~/.config/qtile/vars

set -euo pipefail

choose=$(printf "man\nexec\nhtop\nradeontop" | $menu "Choose:" -l 5 -R)
case $choose in
  man)
    cmdtoman=$(echo "" | $menu "Enter cmd to manual:")
    $term man $cmdtoman
  ;;
  exec)
    cmdtoverbose=$(echo "" | $menu "Enter cmd to verbose:")
    $term $cmdtoverbose
  ;;
  htop)
    $term htop
  ;;
  radeontop)
    $term radeontop
  ;;
  *)
    exit 1
  ;;
esac
