#!/usr/bin/env bash

source ~/.config/qtile/vars

set -euo pipefail

bigfindlines1=$(find $dotdir -maxdepth 1 -printf '%f\n' | tail -n +2 | wc -l)
avconfs=$(find $dotdir -maxdepth 1 -printf '%f\n' | tail -n +2)
conftoed=$(printf "$avconfs" | $menu "Config to edit:" -R -l $bigfindlines1)
$term -c stedit $EDITOR $dotdir$conftoed
