#!/usr/bin/env bash

source ~/.config/qtile/vars

set -euo pipefail

WALMODE=no

# this thing gonna be MASSIVE
# for now qtile, dunst, helix, xresources and gtk is supported

waltheming() {
  wallust run ~/.cache/wallcache
  qtile cmd-obj -o cmd -f reload_config
  xrdb -merge ~/.Xresources
  kill -s USR1 $(pidof st) || echo "no st running"
  pkill dunst || echo "no dunst running"
  kill -s USR1 $(pidof hx) || echo "no helix running"
}

gtktheming() {
  case $choose in
    "Wal")
      choosegtktheme="Qogir-Dark"
      chooseicontheme="Qogir"
    ;;
    "DoomOne")
      choosegtktheme="Qogir-Dark"
      chooseicontheme="Qogir"
    ;;
    "Gruvbox")
      choosegtktheme="gruvbox-dark"
      chooseicontheme="Papirus-Dark"
    ;;
    "Dracula")
      choosegtktheme="Dracula"
      chooseicontheme="Dracula"
    ;;
    "CatppuccinMocha")
      choosegtktheme="Dracula"
      chooseicontheme="Dracula"
    ;;
    "Nord")
      choosegtktheme="Nordic"
      chooseicontheme="Papirus-Dark"
    ;;
    "Everforest")
      choosegtktheme="Qogir-Dark"
      chooseicontheme="Qogir"
    ;;
  esac
  sed -i "s/^gtk-icon-theme-name = .*/gtk-icon-theme-name = \"$chooseicontheme\"/" $HOME/Dotfiles/.gtkrc-2.0
  sed -i "s/^gtk-theme-name = .*/gtk-theme-name = \"$choosegtktheme\"/" $HOME/Dotfiles/.gtkrc-2.0
  sed -i "s/^gtk-icon-theme-name=.*/gtk-icon-theme-name=$chooseicontheme/" $HOME/Dotfiles/.config/gtk-3.0/settings.ini
  sed -i "s/^gtk-theme-name=.*/gtk-theme-name=$choosegtktheme/" $HOME/Dotfiles/.config/gtk-3.0/settings.ini
  sed -i "s|^Net/IconThemeName .*|Net/IconThemeName \"$chooseicontheme\"|" $HOME/Dotfiles/.config/xsettingsd/xsettingsd.conf
  sed -i "s|^Net/ThemeName .*|Net/ThemeName \"$choosegtktheme\"|" $HOME/Dotfiles/.config/xsettingsd/xsettingsd.conf
}

while test $# -gt 0; do
  case "$1" in
    -w)
      if [ $WALMODE == "yes" ]; then
        waltheming
        exit 0
      else
        exit 0
      fi
    ;;
    *)
      printf "[-w] - wallust run\n"
      exit 1
    ;;
  esac
done

choose=$(printf "$themes\nHelix" | $menu "Choose:" -R -l $(printf "$themes\nHelix\n" | wc -l))
if [ $choose == "Wal" ]; then
  sed -i "s/^colors = colors.*/colors = colors.$choose/g" $HOME/Dotfiles/.config/qtile/config.py
  sed -i "s/^theme = .*/theme = \"$choose\"/" $HOME/Dotfiles/.config/helix/config.toml
  sed -i "s/xres-.*/xres-$choose\"/" $HOME/Dotfiles/.Xresources
  gtktheming
  sed -i "7s/^WALMODE=.*/WALMODE=yes/" $HOME/Dotfiles/.config/qtile/scripts/theme-changer
  waltheming
  notify-send "Theme Tool" "Changed Theme to Wallust"
elif [ $choose == "Helix" ]; then
  helixchoose=$(printf "DoomOne\nCatppuccinMocha\nGruvbox\nEverforest\nDracula\nWal\ngruber-darker\nmonokai_pro\nnord-night\ntokyonight\nayu_mirage\ndarcula-solid" | $menu "Choose helix theme:" -R -l 12)
  sed -i "s/^theme = .*/theme = \"$helixchoose\"/" $HOME/Dotfiles/.config/helix/config.toml
  kill -s USR1 $(pidof hx) || echo "no helix running"
  notify-send "Theme Tool" "Changed Helix Theme to $helixchoose"
else
  sed -i "s/^colors = colors.*/colors = colors.$choose/g" $HOME/Dotfiles/.config/qtile/config.py
  sed -i "s/^theme = .*/theme = \"$choose\"/" $HOME/Dotfiles/.config/helix/config.toml
  sed -i "s/xres-.*/xres-$choose\"/" $HOME/Dotfiles/.Xresources
  cp ~/Dotfiles/.config/qtile/themes/dunst-"$choose" $HOME/Dotfiles/.config/dunst/dunstrc
  gtktheming
  sed -i "7s/^WALMODE=.*/WALMODE=no/" $HOME/Dotfiles/.config/qtile/scripts/theme-changer
  qtile cmd-obj -o cmd -f reload_config
  xrdb -merge ~/.Xresources
  kill -s USR1 $(pidof st) || echo "no st running"
  pkill dunst || echo "no dunst running"
  kill -s USR1 $(pidof hx) || echo "no helix running"
  notify-send "Theme Tool" "Changed Theme to $choose"
fi
