backend = "resized"
color_space = "lab"
palette = "dark"
threshold = 10
new_engine = true

[templates]
qtile.template = 'templates/colors-qtile.py'
qtile.target = '~/Dotfiles/.config/qtile/colors.py'

dunst.template = 'templates/colors-dunstrc'
dunst.target = '~/Dotfiles/.config/dunst/dunstrc'

xresources.template = 'templates/colors-xresources'
xresources.target = '~/Dotfiles/.Xresources'
