format = '''
[ $username at $hostname $shell$directory$cmd_duration$git_branch$git_commit$git_status$time](bold white)
[ $character$status](bold white)'''

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
vimcmd_symbol = '[➜](bold cyan)'
vimcmd_replace_symbol = '[➜](bold yellow)'
vimcmd_replace_one_symbol = '[➜](bold yellow)'
vimcmd_visual_symbol = '[➜](bold purple)'

[username]
format = "[$user](bold blue)"
show_always = true

[directory]
style = "bold underline italic blue"

[hostname]
ssh_only = false
format = '[$hostname](bold purple)'

[time]
format = "[$time](bold yellow)"
disabled = false

[cmd_duration]
style = "bold red"

[status]
disabled = false

[shell]
# disabled = false
disabled = true
format = "via [$indicator](bold cyan)"

[git_commit]
only_detached = false
