
format = '''[ $username$directory$character$status](bold white)'''

right_format = '''[$time $cmd_duration$git_branch$git_commit$git_status ](bold white)'''

[character]
success_symbol = '[ ](bold black)'
error_symbol = '[ ](bold black)'

[username]
format = "[ [ $user ](bold black bg:green)](bold green)"
show_always = true

[directory]
format = "[ [$path](bold white bg:black) ](bold green bg:black)"

[hostname]
ssh_only = false
format = '[$hostname](bold purple)'

[time]
format = "[$time](bold dark grey)"
disabled = false

[cmd_duration]
style = "bold red"

[status]
disabled = false

[git_commit]
only_detached = false
