theme = "DoomOne"

[editor]
bufferline = "multiple"
cursorline = true
true-color = true
line-number = "relative"
color-modes = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-type"]

[editor.file-picker]
hidden = true
