theme = "DoomOne"

[editor]
bufferline = "multiple"
cursorline = true
true-color = true
line-number = "relative"
color-modes = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner"]
center = [ "read-only-indicator", "file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "file-type"]
mode.normal = "◉︎"
mode.insert = "◉︎"
mode.select = "◉︎"

[keys.normal]
d = "delete_selection_noyank"
A-d = "delete_selection"
c = "change_selection_noyank"
A-c = "change_selection"

[editor.file-picker]
hidden = false
max-depth = 6
